CREATE TABLE USUARIO(
    IDUSUARIO NUMBER NOT NULL,
    CORREO VARCHAR(30) NOT NULL,
    PASSWORDC VARCHAR(30) NOT NULL,
    PRIMARY KEY(IDUSUARIO)
);

CREATE SEQUENCE SW_S_USUARIO
INCREMENT BY 1 
START WITH 1 
MAXVALUE 99999999 
MINVALUE 1;

CREATE TABLE NEWTON(
    IDNEWTON NUMBER NOT NULL,
    IDUSUARIO NUMBER NOT NULL,
    ECUACION VARCHAR(30) NOT NULL,
    X0 FLOAT NOT NULL,
    XI FLOAT NOT NULL,
    EAa FLOAT NOT NULL,
    PRIMARY KEY(IDNEWTON),
    FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE SEQUENCE SW_S_NEWTON
INCREMENT BY 1 
START WITH 1 
MAXVALUE 99999999 
MINVALUE 1;

CREATE TABLE SECANTE(
    IDSECANTE NUMBER NOT NULL,
    IDUSUARIO NUMBER NOT NULL,
    ECUACION VARCHAR(30) NOT NULL,
    X0 FLOAT NOT NULL,
    X1 FLOAT NOT NULL,
    XI FLOAT NOT NULL,
    EAa FLOAT NOT NULL,
    PRIMARY KEY(IDSECANTE),
    FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE SEQUENCE SW_S_SECANTE
INCREMENT BY 1 
START WITH 1 
MAXVALUE 99999999 
MINVALUE 1;

CREATE TABLE MULLER(
    IDMULLER NUMBER NOT NULL,
    IDUSUARIO NUMBER NOT NULL,
    ECUACION VARCHAR(30) NOT NULL,
    X0 FLOAT NOT NULL,
    X1 FLOAT NOT NULL,
    X2 FLOAT NOT NULL,
    XI FLOAT NOT NULL,
    EAa FLOAT NOT NULL,
    PRIMARY KEY(IDMULLER),
    FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE SEQUENCE SW_S_MULLER
INCREMENT BY 1 
START WITH 1 
MAXVALUE 99999999 
MINVALUE 1;

CREATE TABLE GAUSS3X3(
    IDGAUSS NUMBER NOT NULL,
    IDUSUARIO NUMBER NOT NULL,
    TIPOMATRIZ VARCHAR(30) NOT NULL,
    DATOSMATRIZ VARCHAR(60) NOT NULL,
    X FLOAT NOT NULL,
    Y FLOAT NOT NULL,
    Z FLOAT NOT NULL,
    PRIMARY KEY(IDGAUSS),
    FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE SEQUENCE SW_S_GAUSS3X3
INCREMENT BY 1 
START WITH 1 
MAXVALUE 99999999 
MINVALUE 1;